server:
  port: 8001
  error:
    include-stacktrace: always

spring:
  application:
    name: springboot-bank-system

  datasource:
    url: jdbc:postgresql://localhost:5432/bank_system
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        security: DEBUG